### ISSUE TITLE
Helgoland-webapp loading fail

### ISSUE THREAD

**Issue by danji90** [52North/helgoland#17]
We have deployed the helgoland-test-stable exactly as described in the git documentation on our tomcat in our Linux Centos 7 server: 

- nodejs.x86_64 previously installed

- download and extract test-stable.zip 

- within the helgoland-test-stable folder: npm install, then grunt buildWar with following console results 
[npm_install _logs.txt](https://github.com/52North/helgoland/files/850697/npm_install._logs.txt) , no errors.

- Copy the new War-file from the build folder into tomcat/webapps, new helgoland folder generated, no errors

After these steps we try to access the webapp in the browser using the "IP:port/helgoland". The result is a blank page with the following network errors:
[helgoland_error_install _logs.txt](https://github.com/52North/helgoland/files/850732/helgoland_error_install._logs.txt)

Are we missing a step somewhere? Shouldn't the stable-test version from the master tree be already fully functional without modifying source codes, especially when encountering no errors during the deployment process?

We would be really grateful if someone could help us out with this issue,

Thank you very much,

Daniel

**Comment by janschulte** [comment]
Please try it with the current master branch. The stable-test version seems to be broken. This release was just a 'test' release in the past. Sorry, that it isn't working. I will delete it.

**Comment by danji90** [comment]
Hi Jan,
as we already tried before we installed the stable-test, we tried to install the master version again. We cloned the git repository using https://github.com/52North/helgoland.git , then did npm install (nodejs.x86_64 previously installed), the install process was halted due to errors (see log file 

[npm-debug.txt](https://github.com/52North/helgoland/files/860882/npm-debug.txt).

Are we getting something wrong or are there some faulty files in the repository?

Thanks,

Daniel

**Comment by janschulte** [comment]
I can only just google myself. Because it fails on installing node-canvas, you maybe need to check the following needed [Installation](https://github.com/Automattic/node-canvas#installation)?

**Comment by danji90** [comment]
Hi Jan,
Thank you for your feedback, we finally managed to deploy helgoland master version using one of the commands in the link you sent: 
**sudo yum install cairo cairo-devel cairomm-devel libjpeg-turbo-devel pango pango-devel pangomm pangomm-devel giflib-devel**
Previously, while trying to solve all the errors we actually installed cairo and pango before, but we were still missing giflib-devel, so apparently this was the problem. Yet all these packages are essential for the deployment and don't seem to install automatically with node.js. Maybe you could add this in the git documentation.
Thank you again, kind regards

Daniel
